version: '3.8'

services:
  modubus:
    build: .
    container_name: modubus
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && tail -f /dev/null"
    ports:
      - '3000:3000'
    depends_on:
      - modubus-database
    environment:
      - DATABASE_HOST=modubus-database
      - DATABASE_PORT=3306
      - DATABASE_USER=mysql
      - DATABASE_PASSWORD=mysqlpw
      - DATABASE_NAME=db

  modubus-database:
    image: mysql:8.4.1
    container_name: modubus-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
